server:
  contextPath: /clearbank

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

      
spring:
  datasource:
    url : jdbc:mysql://localhost:3306/clearbank?useSSL=false
    username : clearbankuser
    password : Clearbank#123
  jpa:
    hibernate:
      ddl-auto : update
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5Dialect